FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/chat-server ./cmd/chat-server

FROM scratch
COPY --from=builder /bin/chat-server /chat-server
COPY --from=builder /app/configs /configs

EXPOSE 8080
ENTRYPOINT ["/chat-server"]
