FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/messaging-worker ./cmd/messaging-worker

FROM scratch
COPY --from=builder /bin/messaging-worker /messaging-worker
COPY --from=builder /app/configs /configs

ENTRYPOINT ["/messaging-worker"]
