// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/rpc/proto/calculator.proto

package calculatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OperandA      float64                `protobuf:"fixed64,2,opt,name=operand_a,json=operandA,proto3" json:"operand_a,omitempty"`
	OperandB      float64                `protobuf:"fixed64,3,opt,name=operand_b,json=operandB,proto3" json:"operand_b,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryRequest) Reset() {
	*x = BinaryRequest{}
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryRequest) ProtoMessage() {}

func (x *BinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryRequest.ProtoReflect.Descriptor instead.
func (*BinaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BinaryRequest) GetOperandA() float64 {
	if x != nil {
		return x.OperandA
	}
	return 0
}

func (x *BinaryRequest) GetOperandB() float64 {
	if x != nil {
		return x.OperandB
	}
	return 0
}

func (x *BinaryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UnaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	N             int64                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryRequest) Reset() {
	*x = UnaryRequest{}
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRequest) ProtoMessage() {}

func (x *UnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRequest.ProtoReflect.Descriptor instead.
func (*UnaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UnaryRequest) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *UnaryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CalculationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Operation         string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Result            float64                `protobuf:"fixed64,3,opt,name=result,proto3" json:"result,omitempty"`
	Operands          []float64              `protobuf:"fixed64,4,rep,packed,name=operands,proto3" json:"operands,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ComputationTimeNs int64                  `protobuf:"varint,6,opt,name=computation_time_ns,json=computationTimeNs,proto3" json:"computation_time_ns,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculationResponse) Reset() {
	*x = CalculationResponse{}
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponse) ProtoMessage() {}

func (x *CalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponse.ProtoReflect.Descriptor instead.
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *CalculationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CalculationResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CalculationResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CalculationResponse) GetOperands() []float64 {
	if x != nil {
		return x.Operands
	}
	return nil
}

func (x *CalculationResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CalculationResponse) GetComputationTimeNs() int64 {
	if x != nil {
		return x.ComputationTimeNs
	}
	return 0
}

func (x *CalculationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CalculationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_internal_rpc_proto_calculator_proto protoreflect.FileDescriptor

const file_internal_rpc_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"#internal/rpc/proto/calculator.proto\x12\n" +
	"calculator\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\rBinaryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\toperand_a\x18\x02 \x01(\x01R\boperandA\x12\x1b\n" +
	"\toperand_b\x18\x03 \x01(\x01R\boperandB\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.calculator.BinaryRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\fUnaryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\f\n" +
	"\x01n\x18\x02 \x01(\x03R\x01n\x12B\n" +
	"\bmetadata\x18\x03 \x03(\v2&.calculator.UnaryRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x02\n" +
	"\x13CalculationResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x01R\x06result\x12\x1a\n" +
	"\boperands\x18\x04 \x03(\x01R\boperands\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12.\n" +
	"\x13computation_time_ns\x18\x06 \x01(\x03R\x11computationTimeNs\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"|\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xc7\x04\n" +
	"\x11CalculatorService\x12A\n" +
	"\x03Add\x12\x19.calculator.BinaryRequest\x1a\x1f.calculator.CalculationResponse\x12F\n" +
	"\bSubtract\x12\x19.calculator.BinaryRequest\x1a\x1f.calculator.CalculationResponse\x12F\n" +
	"\bMultiply\x12\x19.calculator.BinaryRequest\x1a\x1f.calculator.CalculationResponse\x12D\n" +
	"\x06Divide\x12\x19.calculator.BinaryRequest\x1a\x1f.calculator.CalculationResponse\x12C\n" +
	"\x05Power\x12\x19.calculator.BinaryRequest\x1a\x1f.calculator.CalculationResponse\x12F\n" +
	"\tFactorial\x12\x18.calculator.UnaryRequest\x1a\x1f.calculator.CalculationResponse\x12F\n" +
	"\tFibonacci\x12\x18.calculator.UnaryRequest\x1a\x1f.calculator.CalculationResponse\x12D\n" +
	"\vHealthCheck\x12\x19.calculator.HealthRequest\x1a\x1a.calculator.HealthResponseB@Z>github.com/distributed-systems/internal/rpc/proto;calculatorpbb\x06proto3"

var (
	file_internal_rpc_proto_calculator_proto_rawDescOnce sync.Once
	file_internal_rpc_proto_calculator_proto_rawDescData []byte
)

func file_internal_rpc_proto_calculator_proto_rawDescGZIP() []byte {
	file_internal_rpc_proto_calculator_proto_rawDescOnce.Do(func() {
		file_internal_rpc_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_calculator_proto_rawDesc), len(file_internal_rpc_proto_calculator_proto_rawDesc)))
	})
	return file_internal_rpc_proto_calculator_proto_rawDescData
}

var file_internal_rpc_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_rpc_proto_calculator_proto_goTypes = []any{
	(*BinaryRequest)(nil),         // 0: calculator.BinaryRequest
	(*UnaryRequest)(nil),          // 1: calculator.UnaryRequest
	(*CalculationResponse)(nil),   // 2: calculator.CalculationResponse
	(*HealthRequest)(nil),         // 3: calculator.HealthRequest
	(*HealthResponse)(nil),        // 4: calculator.HealthResponse
	nil,                           // 5: calculator.BinaryRequest.MetadataEntry
	nil,                           // 6: calculator.UnaryRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_internal_rpc_proto_calculator_proto_depIdxs = []int32{
	5,  // 0: calculator.BinaryRequest.metadata:type_name -> calculator.BinaryRequest.MetadataEntry
	6,  // 1: calculator.UnaryRequest.metadata:type_name -> calculator.UnaryRequest.MetadataEntry
	7,  // 2: calculator.CalculationResponse.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 3: calculator.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 4: calculator.CalculatorService.Add:input_type -> calculator.BinaryRequest
	0,  // 5: calculator.CalculatorService.Subtract:input_type -> calculator.BinaryRequest
	0,  // 6: calculator.CalculatorService.Multiply:input_type -> calculator.BinaryRequest
	0,  // 7: calculator.CalculatorService.Divide:input_type -> calculator.BinaryRequest
	0,  // 8: calculator.CalculatorService.Power:input_type -> calculator.BinaryRequest
	1,  // 9: calculator.CalculatorService.Factorial:input_type -> calculator.UnaryRequest
	1,  // 10: calculator.CalculatorService.Fibonacci:input_type -> calculator.UnaryRequest
	3,  // 11: calculator.CalculatorService.HealthCheck:input_type -> calculator.HealthRequest
	2,  // 12: calculator.CalculatorService.Add:output_type -> calculator.CalculationResponse
	2,  // 13: calculator.CalculatorService.Subtract:output_type -> calculator.CalculationResponse
	2,  // 14: calculator.CalculatorService.Multiply:output_type -> calculator.CalculationResponse
	2,  // 15: calculator.CalculatorService.Divide:output_type -> calculator.CalculationResponse
	2,  // 16: calculator.CalculatorService.Power:output_type -> calculator.CalculationResponse
	2,  // 17: calculator.CalculatorService.Factorial:output_type -> calculator.CalculationResponse
	2,  // 18: calculator.CalculatorService.Fibonacci:output_type -> calculator.CalculationResponse
	4,  // 19: calculator.CalculatorService.HealthCheck:output_type -> calculator.HealthResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_rpc_proto_calculator_proto_init() }
func file_internal_rpc_proto_calculator_proto_init() {
	if File_internal_rpc_proto_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_calculator_proto_rawDesc), len(file_internal_rpc_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_proto_calculator_proto_goTypes,
		DependencyIndexes: file_internal_rpc_proto_calculator_proto_depIdxs,
		MessageInfos:      file_internal_rpc_proto_calculator_proto_msgTypes,
	}.Build()
	File_internal_rpc_proto_calculator_proto = out.File
	file_internal_rpc_proto_calculator_proto_goTypes = nil
	file_internal_rpc_proto_calculator_proto_depIdxs = nil
}
